import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Frontend } from './frontend'
import { Header } from './header';
import { PropsWithChildren } from 'react';
import { getPublicPolicySetting } from '@/services/policyService';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Redeeming your ENS',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: PropsWithChildren<{ params: { event: string } }>) {
  const config = getPublicPolicySetting(props.params.event);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Frontend config={config} >
          <Header />
          {props.children}
        </Frontend>
      </body>
    </html>
  )
}
