import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Frontend } from './frontend'
import { ConnectButton } from '@rainbow-me/rainbowkit'
import '@rainbow-me/rainbowkit/styles.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Redeeming your ENS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Frontend>
          <nav className="bg-blue-600 p-4 text-white">
            <div className="container mx-auto">
              <h1 className="text-2xl font-semibold">ETHGlobal Redeem Tool</h1>
              <ConnectButton />
            </div>
          </nav>
          {children}
        </Frontend>
      </body>
    </html>
  )
}
